on:
  workflow_dispatch:
    inputs:
      id:
        description: 'run identifier'
        required: false
      job:
        required: true
jobs:
  build:
    name: Workflow ID Provider
    runs-on: ubuntu-latest
    steps:
      - name: digger run
        uses: diggerhq/digger@develop
        with:
          setup-aws: false
          disable-locking: true
          digger-token: ${{ secrets.DIGGER_TOKEN }}
          digger-hostname: 'https://cloud.uselemon.cloud'
          digger-organisation: 'digger'
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
